### ISSUE TITLE
MyForecast - Weather Data Refresh - Error While connecting to WeatherUnderground. Please, Try again in a few minutes

### ISSUE THREAD

**Issue by bravoland** [nelinory/myForecast#12]
is this still a working program?  i get the message above when i click on it in media center

<?xml version="1.0" encoding="utf-8"?>
<Configuration>
  <ApiKey>***REMOVED**</ApiKey>
  <LocationCode>zmw:73112.5.99999</LocationCode>
  <WeatherUnit>Imperial</WeatherUnit>
  <RefreshRateInMinutes>10</RefreshRateInMinutes>
  <ClockTimeFormat>Hours12</ClockTimeFormat>
  <Language>EN</Language>
</Configuration>

log file shows
01/24/2018 16:01:24.051		Error		Unable to connect to the remote server
Stack:   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at myForecast.WeatherModel.LoadWeatherData()

**Comment by bravoland** [comment]
issue was related to my internet connection :(
